### ISSUE TITLE
Review and suggest changes

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/threesixtygiving.github.io#2]
@timgdavies says "...if you could look at current docs at docs.threesixtygiving.org and either make edits direct _or_ put together a tracked changes document, I can merge all that in on Tuesday/Wednesday"

**Comment by stevieflow** [comment]
In terms of typos and changes, then see: https://github.com/ThreeSixtyGiving/threesixtygiving.github.io/pull/8

Ill document wider suggested changes separately
