### ISSUE TITLE
Should we point people to the Registry to register / claim their prefix?

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/threesixtygiving.github.io#4]
The documentation states:

> To get started with 360 Giving, register a publisher through the online service here and follow the instructions from your dashboard to create an organisation record.

Ill rephrase this, but the guidance will still point to this resource.  Our decisions are whether we want to a) continue with this route and/or b) have this as a starting point

**Comment by timgdavies** [comment]
On the new site we'll point people to /register/ and encourage them to get in touch with us for the time being... and then we can get having a better self-registration system onto the ToDo list...
