### ISSUE TITLE
Provide a table for all fields of the standard

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/threesixtygiving.github.io#5]
The table at http://docs.threesixtygiving.org/publish/#toc2 - whilst acknowledging that this is the summary sheet - doesnt detail other available fields (eg Classifications)

How best to resolve this?  Perhaps a page for all 360 Giving fields, and also a full summary sheet (if that makes sense)

Increasingly, users will want to know the full scope of the standard - so making this available will be important

**Comment by stevieflow** [comment]
I guess making a balance between this and http://docs.threesixtygiving.org/js/docson/index.html#/assets/standard/schema/360-giving-schema.json is the focus -

**Comment by timgdavies** [comment]
I've started moving documentation into the Standard repository, and have a working model of this here: https://github.com/ThreeSixtyGiving/standard/blob/master/documentation/reference.md
