### ISSUE TITLE
Archiving this repo

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/threesixtygiving.github.io#9]
Once issues have been resolved, we could / should archive this (and consider URL redirects)

**Comment by caprenter** [comment]
There is no mechanism to archiving a repo as such. In the past we have spoken about creating a new github organisation to move archive projects to, but this may not be ideal.

I've altered the description of this repo to say that it is no longer used. So I think we can close this issue, and leave the repo as it is

**Comment by stevieflow** [comment]
Thanks
